# Generated by Django 3.0.7 on 2020-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='templates/homepage/assets/team/')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('university', models.CharField(max_length=320)),
                ('mail', models.EmailField(max_length=254)),
                ('linkedin', models.TextField(max_length=333)),
                ('github', models.TextField(max_length=333)),
            ],
        ),
    ]
