# Generated by Django 3.0.7 on 2020-06-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200604_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(upload_to='C:\\Users\\USER\\Desktop\\MyProjects\\Visuel learning with django\\src\\static/assets/team/'),
        ),
    ]
