# Generated by Django 3.0.7 on 2020-06-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200604_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(max_length=500, upload_to='C:\\Users\\USER\\Desktop\\MyProjects\\Visuel learning with django\\src\\homepage/static/assets/team/'),
        ),
    ]
